### ISSUE TITLE
<input type="width|height"> vs <extent width="" height="">

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/MapML#117]
Would it be feasible to (re-)use the HTML `width` and `height` attributes on the `<extent>` element:

```html
<extent width="" height="">
  ...
</extent>
```
as opposed to:

```html
<extent>
  <input type="width" ...>
  <input type="height" ...>
   ...
</extent>
```

?

**Comment by prushforth** [comment]
Interesting idea. I'll ponder a bit. Need a way to serialize those properties of the map as variables for transfer to the server.

**Comment by prushforth** [comment]
I wonder if we could use the output element, using as input the input type=location of the axes that can yield an appropriate width and height.  Was reading this article and that at least seems plausible https://www.scottohara.me/blog/2019/07/10/the-output-element.html

**Comment by prushforth** [comment]
I don't know if output elements get serialized with the inputs, maybe if it has a name?

**Comment by prushforth** [comment]
> I don't know if output elements get serialized with the inputs, maybe if it has a name?

No, they [don't](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/output): "contents are NOT submitted during form submission"

**Comment by Malvoz** [comment]
My thinking was that maybe we could avoid introducing 2 new `type` states in this case, that'd be nice, but perhaps we cannot. I'll close this for now.

**Comment by prushforth** [comment]
I agree that extra `type` states are a barrier, I would love to figure a way around it but so far haven't thought of any.  One idea that occurred to me is that extents are a type of `location`, just as `tile` and `feature` are.  So if there was a grammar associated to `<input type="location" ...>` that allowed to specify properties to be serialized, in a way similar to the way we are currently using `<input type="location" axis="latitude" ...>` (for example), we could refer to the property of the extent "location" that we want to serialize, including axis, of course, but possibly including the (dynamic, responsive) `width` and `height` properties of the extent "location".  I don't know if that makes sense.  Anyway, hopefully somebody will see this and bring it up when push comes to shove :-).
