### ISSUE TITLE
Remove mentions of rel=search

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/MapML#119]
The "Changes since the previous draft" section says: "_Remove reference to link@rel=search, which is not supported._", however the [table of `rel` values ](https://maps4html.org/MapML/spec/#rel-values) still has the `search` value in it, it should be removed.

**Comment by prushforth** [comment]
Robert, I was thinking it would be reasonable to remove all the rel values that we don't implement, specifically:

- author
- bookmark
- next
- west
- southwest
- south
- southeast
- east
- northeast
- north
- northwest
- panto

Some of these were based on misconceptions that I once held, others I'm unsure why I added them.  Maybe just to have a document that said something significant.  

Anyway, they're just baggage now.
