### ISSUE TITLE
Can we remove the "Glossary of Terms and Datatypes" section?

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/MapML#134]
Is https://maps4html.org/MapML/spec/#glossary redundant now that ReSpec generates an [Index of terms](https://maps4html.org/MapML/spec/#index)? Or is a stand-alone glossary still valuable? e.g. for OGC terms (https://github.com/Maps4HTML/MapML/issues/40).

If there are missing terms in the generated index we need to properly utilize `<dfn>` as appropriate (https://respec.org/docs/#definitions-and-linking).

**Comment by Malvoz** [comment]
If we're going to have a glossary, should terms defined in https://maps4html.org/HTML-Map-Element-UseCases-Requirements/#intro-glossary be duplicated in this spec? Or can we refer to that section of the report?

**Comment by prushforth** [comment]
I think the automated respec approach will work, so yes we can delete the section.  I would prefer to not import the terms and definitions from the UCR at this point, as some re-work may be necessary.
