### ISSUE TITLE
Add the `nopan` keyword to `controlslist`

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/MapML#137]
When writing https://github.com/Maps4HTML/MapML/issues/88#issuecomment-718808340 I was reminded that we should add the `nopan` keyword to the `controlslist` attribute, it disables default controls for panning.

This is needed because default controls for panning are currently [expected](https://maps4html.org/MapML/spec/#expose-a-user-interface-to-the-user) to be exposed to the user by the UA.

**Comment by prushforth** [comment]
I think that the mention of pan controls under "expected" may not have been thought through.  Adding to the spec implies that we're ready to add it to the implementation, and while I am willing, I believe that panning and zooming require more discussion and research.

Ideally we would keep the spec in sync by removing the mention of pan controls until we're ready to implement something.

**Comment by Malvoz** [comment]
Keep in mind that these controls are not required by implementers:

> This user interface should include [...]

(this is true HTML video/audio controls as well)

_should_ vs _must_ is an important distinction. 

> I believe that panning and zooming require more discussion and research.

I agree. It was briefly discussed in https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/issues/148.

> Ideally we would keep the spec in sync by removing the mention of pan controls until we're ready to implement something.

It's fine that the polyfill is behind the spec though, and again, they're not required.

Ultimately, not providing controls to pan is disregarding people that are unable to perform swipe or drag gestures, and probably screen reader users on touch devices as well (where swiping is equal to tabbing). I realize that most authors are likely not going to want to include controls to pan (status quo). But that should be up to each author to decide (i.e. `controlslist="nopan"`). And authors who do want to provide these controls should not have to implement custom controls.

Therefore I think it's better to expect controls for panning than not to expect them. And we can always remove the expectation later, if they're deemed not necessary.

**Comment by prushforth** [comment]
OK
