### ISSUE TITLE
Implicit ARIA roles for map elements

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/MapML#149]
As suggested by @shepazu (at approx. 37:30 in the [2020 TPAC talk on Maps for HTML](https://www.w3.org/2020/10/TPAC/maps_for_html_community_group.html#talk)) and also discussed in https://github.com/Maps4HTML/Web-Map-Custom-Element/pull/151, it is conceivable that certain map elements (including `map`) have implicit ARIA roles, such that users of ATs can identify the context in which they're in.

I believe we've said that [interactive maps](https://maps4html.org/HTML-Map-Element-UseCases-Requirements/#use-case-create-map) and [static maps](https://maps4html.org/HTML-Map-Element-UseCases-Requirements/#use-case-static-map) are distinct enough that they may deserve separate ARIA roles. For example `map` and `staticmap`.

**Comment by Malvoz** [comment]
The definitions of implicit ARIA roles belong in [MapML AAM](https://github.com/Maps4HTML/MapML/issues/165), but since we're likely to establish some of these early on - where do we define them in the meantime? Perhaps the elements' definitions is a good place (along with the <q>Allowed ARIA role attribute values</q> and <q>Allowed ARIA state and property attributes</q>)?

**Comment by prushforth** [comment]
I do believe the ARIA roles should at least begin life in the MapML spec, in perhaps the elements' definitions as you suggest. If it gets too cumbersome we can factor into its own document.  

BTW although a static map may not have obviously interactive features, we should try to adhere to their map-ness.  That is, they should be able to have features, location, extent, and (perhaps) layers, and so on, even if they can't zoom or pan.  If you were flying in an airplane with GPS on, a static map of the Pacific Ocean could still put your geolocation in the correct spot, if that was the use case.
