### ISSUE TITLE
Does mapml have a notion of layer hierarchy

### ISSUE THREAD

**Issue by pvgenuchten** [Maps4HTML/MapML#161]
I didn't find any references to building layer hierarchy in mapml, is it possible to nest layers in other layers, or does a concept of layerfolder/layergroup exist.

In traditional GIS, layer hierarchy is a common approach to organize many layers

**Comment by prushforth** [comment]
Layers cannot be nested, however, a layer may have any number of tile, image and feature templates. The limitation on that is comprehensibility and, so far, we have not created an affordance mechanism to control (turn on / off, adjust opacity etc) such templates.

**Comment by Malvoz** [comment]
There _may_ be a need/use cases for grouping layers however: https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/issues/179#issuecomment-761692476. One such use case may be tying [metadata](https://github.com/Maps4HTML/MapML/issues/130#issuecomment-720621451) to a certain layer or group of layers.
