### ISSUE TITLE
 Provide a clear way for a MapML layer to indicate its spatial extent

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/MapML#17]
This relates to the ability to [zoom to a layer](https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/77) or [derive a map default location based on the union of extents of its layers](https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/78).

**Comment by pomakis** [comment]
Couldn't this be as simple as adding optional minLat,minLon,maxLat,maxLon meta tags to the head?  E.g.:

```
<meta name="minLat" content="42.5"/>
<meta name="minLon" content="-142.2"/>
<meta name="maxLat" content="74.0"/>
<meta name="maxLon" content="48.3"/>
```

A layer's spatial extent should be invariant of its zoom level.  And requiring it to be expressed in WGS84 Geographic (regardless as to the projection being served) keeps things simple and provides the easiest and most global coordinate system to work with.

I suppose that alternately, if you disagree with bringing WGS84 Geographic into the equation, you could require the spatial extent to be expressed in the coordinate system of the projection being served.  E.g.:

```
<meta name="projection" content="OSMTILE"/>
<meta name="minX" content="-15800000"/>
<meta name="minY" content="5270000"/>
<meta name="maxX" content="-5740000"/>
<meta name="maxY" content="12600000"/>
```

I'd be okay with either.  If the MapML server or MapML document writer isn't sophisticated enough to report a spatial extent, or if the client isn't sophisticated enough to interpret or make use of it, then so be it; tiles will be requested outside of the spatial extent of the layer, but things will continue to work.

**Comment by prushforth** [comment]
I think the meta elements should be used by the server to reflect properties of *this* document.  

But I agree that there should be a simple way for the server to describe the extent of the content on the server.  

In staring at a 'static' map document for a while, I think maybe pushing what used to be 

```
<input type='xmin'...>
<input type='ymin'...>
<input type='xmax'...>
<input type='ymax'...>
```

onto the `<extent>` element might be workable:

```
<extent units="OSMTILE" xmin="pixels-at-some-z" ymin="pixels..." xmax="..." ymax="...">
...
</extent>
```

the question then becomes how to tell the client at what zoom those bounds are.

As you suggest it would be better to use a coordinate system that you don't have to specify the zoom value for, such as the PCRS or GCRS.  

My concern with GCRS lat/lon (possibly from my own ignorance) is for a projection like APSTILE, a bounding box can span the pole, and both meridians.  Is there any value to specifying a bbox in lat/lon values for such a projection?

If `<extent units="OSMTILE">` was renamed to `<extent projection="OSMTILE">` then maybe something like
`<extent projection="OSMTILE" units="GCRS" ...> `
could be used to distinguish what subordinate coordinate system was used to encode the xmin,ymin,xmax,ymax.  Would need to be careful about what is meant by ymin/ymax, since the TCRS y axis is positive downwards.  Maybe left/right/top/bottom would work better.

I know that some people in the OGC would have kittens if the word "projection" is used, but you can't please everybody.

Finally, each link@tref can have an independent bounds, so it might be worthwhile allowing such attributes as described above on a per-link@tref basis.  That way (a smart client) would know to not issue requests that would just result in 404 traffic.

**Comment by prushforth** [comment]
In the meantime before we think up a new and explicit way to allow the map author to provide bounds, I think it would be reasonable to use the bounds that can be derived from a link template's associated <input min="..." max="..."> values.  In the case where the actual bounds are some small area that would cover a 2px X 2px sub-area of the tile at zoom=0 or other low zoom value, I think a workaround would be for the server to provide the bounds at a higher zoom value.  

For example, a map document such as this:

```
<mapml>
  <head>
    <title>Canada Base Map - Transportation (CBMT)</title>
    <meta http-equiv="Content-Type" content="text/mapml;projection=CBMTILE"/>
    <meta charset="utf-8"/>
    <meta name="projection" content="CBMTILE"/>
    <meta name="zoom" content="0"/>
    <base href="/api/beta/mapml/en/cbmtile/cbmt/"/>
    <link rel="license" href="https://www.nrcan.gc.ca/earth-sciences/geography/topographic-information/free-data-geogratis/licence/17285" title="Canada Base Map © Natural Resources Canada"/>
    <link rel="zoomin" href="/api/beta/mapml/en/cbmtile/cbmt/?z=18" type="text/mapml"/>
  </head>
  <body>
    <extent units="CBMTILE" method="GET">
      <input name="z" type="zoom" value="0" min="0" max="17"/>
      <input name="y" type="location" units="tilematrix" axis="row"/>
      <input name="x" type="location" units="tilematrix" axis="column"/>
      <link rel="tile" tref="https://geoappext.nrcan.gc.ca/arcgis/rest/services/BaseMaps/CBMT3978/MapServer/tile/{z}/{y}/{x}?m4h=t"/>
    </extent>
  </body>
</mapml>
```

might have an actual bounds that is around a single country or province or smaller unit, so serving an
<input type="zoom" value="0" min="0" max="17"> would only allow an associated location input to specify the bounds at zoom=0, or default bounds from the TCRS, whereas if you specified the zoom as 

```
<mapml>
  <head>
    <title>Canada Base Map - Transportation (CBMT)</title>
    <meta http-equiv="Content-Type" content="text/mapml;projection=CBMTILE"/>
    <meta charset="utf-8"/>
    <meta name="projection" content="CBMTILE"/>
    <meta name="zoom" content="17"/>
    <base href="/api/beta/mapml/en/cbmtile/cbmt/"/>
    <link rel="license" href="https://www.nrcan.gc.ca/earth-sciences/geography/topographic-information/free-data-geogratis/licence/17285" title="Canada Base Map © Natural Resources Canada"/>
    <link rel="zoomin" href="/api/beta/mapml/en/cbmtile/cbmt/?z=18" type="text/mapml"/>
  </head>
  <body>
    <extent units="CBMTILE" method="GET">
      <input name="z" type="zoom" value="17" min="0" max="17"/>
      <input name="y" type="location" units="tilematrix" axis="row" min="..." max="..."/>
      <input name="x" type="location" units="tilematrix" axis="column" min="..." max="..."/>
      <link rel="tile" tref="https://geoappext.nrcan.gc.ca/arcgis/rest/services/BaseMaps/CBMT3978/MapServer/tile/{z}/{y}/{x}?m4h=t"/>
    </extent>
  </body>
</mapml>
```

then the location inputs for tile row/col could specify their min/max at zoom=17 and would thus provide a more precise bounds for the service as a whole, resulting in fewer / no 404s for tiles not found.

I think the incentives for providing precise min/max values on the location inputs are appropriate, in that if the map author owns the service they will be incentivized to provide precise bounds, and if the map author does not own the service, and perhaps doesn't care if the map gets many 404s or default tiles their site will get a bad reputation from users (who may receive a bad map user experience) and possibly blocked by the map provider if their map requests too many non-existent tiles. 

I am not convinced that adding a second way to provide bounds is going to make the provision of bounds by the map author any more likely, and it will make the code more error prone / non-DRY.

**Comment by prushforth** [comment]
I went and added the min/max of the axis to the [`<input type=location>`](http://geogratis.gc.ca/api/beta/mapml/en/cbmtile/cbmt/?alt=xml) 

As of right now, I am not capturing and storing the extent on a per-`<link tref="...">`-basis, but if this works out for constraining the client layer bounds, that's what I plan to do.  

Feedback appreciated.

**Comment by prushforth** [comment]
Based on our discussion, I think we've agreed that this is the preferred mechanism for identifying bounds per tref, so allow me to close this, and feel free to discuss more or re-open if need be.

**Comment by joanma747** [comment]
Is there any need to define 'tilematrix' axis value bounds for each zoom level?. In WMTS, this is done by providing a TileMatrixSetLimits data structure for each layer a service offers. In thiis case I wonder if we could use and optional internal element in input. Something like this:
```html
<input name="y" type="location" units="tilematrix" axis="row" min="..." max="...">
<bounds z=3 min="3" max="7"/>
<bounds z=4 min="7" max="15"/>
<bounds z=5 min="14" max="30"/>
</input>
```

In the example, the bounds min and max values refer to the min and max values of 'y' for a given value of 'z'. Just an idea.

**Comment by prushforth** [comment]
You have to enclose angle brackets etc in backtics. (_Edit by @Malvoz: backticks added to code example in https://github.com/Maps4HTML/MapML/issues/17#issuecomment-425708414_)

The input element can have no children in HTML, so that's the way we should keep it in MapML. 

But its not necessary anyway, because we can achieve what you are trying for by providing multiple templates with non-overlapping zoom min/max inputs. I think, assuming we can have more than a single zoom input in an extent.
