### ISSUE TITLE
Referencing UCR-MapML-Matrix

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/MapML#172]
The [Use Cases and Requirements](https://maps4html.org/MapML/spec/#use-cases-and-requirements) section currently states:

> This document is being [evaluated](https://github.com/Maps4HTML/MapML/issues?q=is%3Aissue+is%3Aopen+label%3A%22Requirements+Evaluation%22) against the [_Use Cases and Requirements for Standardizing Web Maps_](https://maps4html.org/HTML-Map-Element-UseCases-Requirements/).

IMO this section should reference the UCR MapML Fullfillment Matrix, I was thinking something along the lines of (improvements are welcome, of course):

> This document is being [evaluated](https://github.com/Maps4HTML/MapML/issues?q=is%3Aissue+is%3Aopen+label%3A%22Requirements+Evaluation%22) against the [_Use Cases and Requirements for Standardizing Web Maps_](https://maps4html.org/HTML-Map-Element-UseCases-Requirements/).
>
> See the [_MapML Use Case, Requirement, and Capability Matrix_](https://maps4html.org/UCR-MapML-Matrix/mapml-ucrs-fulfillment-matrix.html) for how MapML compares in capabilities in contrast to existing popular web mapping libraries.

But in this case, is linking <q>evaluated</q> to the [evaluation issues](https://github.com/Maps4HTML/MapML/issues?q=is%3Aissue+is%3Aopen+label%3A%22Requirements+Evaluation%22) redundant? Although it encourages others to engage in the evaluation, I'm not sure it's really all that useful.

**Comment by Malvoz** [comment]
The MapML Proposal has a [similar section](https://github.com/Maps4HTML/MapML-Proposal#use-cases-and-requirements) that should reflect any such changes.

**Comment by prushforth** [comment]
> IMO this section should reference the UCR MapML Fullfillment Matrix, I was thinking something along the lines of

Looks good to me.

> But in this case, is linking evaluated to the evaluation issues redundant? Although it encourages others to engage in the evaluation, I'm not sure it's really all that useful.

I have found that when discussing the feature requirements, it can be quite surprising what is and is not a shared understanding, so I thought and think it might be useful to have a place for discussion.  In fact if it's not obvious that a requirement is fulfilled by an example, it should be possible to link to that discussion from the UCR Fulfillment matrix and/or the example itself to find out the why's and the wherefores of requirements undershoot.
