### ISSUE TITLE
Transfer evaluation issues to UCR-MapML-Matrix?

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/MapML#173]
I wonder if https://github.com/Maps4HTML/UCR-MapML-Matrix/issues/ is a better home for the [evaluation issues](https://github.com/Maps4HTML/MapML/issues?q=is%3Aissue+is%3Aopen+label%3A%22Requirements+Evaluation%22).

**Comment by Malvoz** [comment]
Side note: I think it'd be ideal if each comment in https://github.com/Maps4HTML/MapML/issues/102 is separated into its own issue as it makes them easier to discuss. This could be done as part of transferring the issues, which I'm happy to do.

**Comment by prushforth** [comment]
[Transferred](https://github.com/Maps4HTML/UCR-MapML-Matrix/issues/32)
