### ISSUE TITLE
Link to github from spec(s)

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/MapML#19]
Many specs link to their corresponding github repo under "Participate" which is helpful for people who landed on a spec and wish to contribute to it. This goes for other Maps4HTML repositories aswell.

:)

**Comment by prushforth** [comment]
Thanks for this comment. There are links under "How to provide feedback", to the CG mailing list and the issues on this repo. I think I could expand the text of that section a bit to explain that contributions are welcome under the W3C Software and Document license or as part of the OGC testbed process which has similar IP considerations. 

Is there a more prominent position that you would like to see "How to Participate" info under?

**Comment by Malvoz** [comment]
Sorry for not being more clear about the desired positioning (I instinctly look for the repo link early in the document), specs vary in how they word the description for the github link - it's usually "Issue tracking" or "Participate" as shown in the images below:

### Examples:
<hr>
<img src="https://user-images.githubusercontent.com/26493779/42229557-09b75030-7ee7-11e8-986b-54d1b768b6f8.png" width="500">
<hr>
<img src="https://user-images.githubusercontent.com/26493779/42229361-99387bcc-7ee6-11e8-8179-898bbad14b21.png" width="500">

**Comment by prushforth** [comment]
OK, thanks for that feedback.  I picked Mike West's style of "Participate" and "Feedback" links and added them to [MapML ](https://maps4html.github.io/MapML/spec/)and the proposal [spec](https://maps4html.github.io/HTML-Map-Element/spec/) for HTML's `<map>` element.  If that's approximately what you were looking for, go ahead and close this issue or comment further.

**Comment by bkardell** [comment]
I _believe_ ReSpec will do that for you if you add the `github` property to your config pointing to this repo.     I think it is worth doing if you can because honestly, this sent me on about a 15 minute diversion of trying to determine where the repo was so I could open an issue

**Comment by AmeliaBR** [comment]
Here's the ReSpec docs for the config option @bkardell mentioned:
https://github.com/w3c/respec/wiki/github

(I think it was only added in the past few years, probably after the original drafts of this spec.)

I also agree that it's worth linking things up officially to make it easier for people to submit comments via GitHub.  I'll try to submit a PR to that effect this week.

**Comment by Malvoz** [comment]
@prushforth Setting up the ReSpec config is really helpful, it reveals quite a few issues in the current document, but also does things like generate TOC and an index of terms (defined by the MapML spec or by reference), I have a branch that I've spent way too much time on today, familiarizing myself with ReSpec: https://github.com/Malvoz/MapML/tree/respec.

 I refrained from creating a PR as we've had no coordination about this. And because it's been a bit of a learning process, it's all in one big commit.

**Comment by prushforth** [comment]
I pulled your respec branch.

> I refrained from creating a PR as we've had no coordination about this. And because it's been a bit of a learning process, it's all in one big commit.

Maybe we could move your name from Author to Editors?  Since you've done so much editing recently, that seems appropriate to me.

What else is impacted as a result of ReSpec?  I guess I will have to learn ReSpec, which is probably in the cards anyway, but if it is really a technology change and not so much a content change, but sets us up for the next phase of edits to content, I think that's probably a big win?

Thanks for taking so much of your time to do this.  I imagine ReSpec will be an eventual time saver, at least I hope it will be.

**Comment by Malvoz** [comment]
> Maybe we could move your name from Author to Editors?

I think that sounds reasonable.

> What else is impacted as a result of ReSpec?

There's some automation, e.g.:
- The date of when the spec was last changed.
- The entire "Conformance" section (https://github.com/w3c/respec/wiki/conformance); dynamically adds keywords "MAY, MUST, MUST NOT, and SHALL" (etc.) based on usage in the actual spec text.
- Generates a "References" section, where linked references will either be added to a "Normative" or "Informative" section, depending on if the reference was placed in a section with `class="informative"` (we should review if more sections should be informative than currently is in the branch).
- Automatic detection of linked external references (https://github.com/w3c/respec/wiki/xref):

<img width="500" src="https://user-images.githubusercontent.com/26493779/89956165-e95fc800-dc34-11ea-8239-d883cccea0cc.png">

- Terms are defined using `<dfn>` (https://github.com/w3c/respec/wiki/ReSpec-Editor's-Guide#definitions-and-linking),  when you click on a defined term you can see where in the document it has been referenced:
  <img width="500" src="https://user-images.githubusercontent.com/26493779/89954390-42c5f800-dc31-11ea-8b5c-5f8e1dcffedb.png">
  For example "Map Markup Language" is now a defined term. And we _could_ (not done yet) export those terms, so that other specs can reference them (https://github.com/w3c/respec/wiki/data-export).

> but if it is really a technology change and not so much a content change, but sets us up for the next phase of edits to content, I think that's probably a big win?

I believe this is an improvement, and I find that the generated index and references section helps in realizing when something's not marked up/referenced correctly, things we'd perhaps not notice otherwise. And perhaps more importantly, I think spec reviewers can appreciate those sections too.

As far as content goes, I did change the use of "`@`" symbols, mainly because I don't see it used in other specs, so changed e.g. "`layer@src`" to "the `layer` element's `src` attribute"~. And other subtle things, like making sure every content attribute's description ends with a dot, and the sentence starts with a capital letter... _can't_ let that slide.

**Comment by Malvoz** [comment]
ReSpec integration happened in https://github.com/Maps4HTML/MapML/pull/126, there is certainly room for improvement and any help is appreciated.

The main issue here has been adressed, please open new issues regarding the ReSpec integration if needed.
