### ISSUE TITLE
"tile" coordinate reference system axis names

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/MapML#20]
Currently the [spec has unique axis names](https://maps4html.github.io/MapML/spec/#attr-input-axis-keywords) within a tiled CRS, for all the [associated CRS](https://maps4html.github.io/MapML/spec/#attr-input-units-keywords): tilematrix (row,column); tcrs (x,y), pcrs (easting, northing), gcrs (latitude, longitude), and map (i, j).

The axis name is  used by the client to identify in what associated CRS a location input (`<input@type=location>`)'s relative location (relative to a tile or the extent location identified by `@position`) is required to be submitted by the extent ([example](http://geogratis.gc.ca/api/beta/mapml/en/cbmtile/precipitation/?alt=xml): inputs which have `@position="..."`).

If we want to continue to be able to use this technique to distinguish which associated CRS to serialize for relative positions, we will need to come up with unique axis names for the "tile" associated CRS (which would have axis values from 0,0 at the upper left to 255,255 at the lower right). 

These axis names' use case would be support for GetFeatureInfo from a [WMTS](http://portal.opengeospatial.org/files/?artifact_id=35326) (section 7.3.2).

Or some other model for the attribute names etc. which would be a bit disruptive at this point, but if it makes things better (more self-explanatory), perhaps.

Bikeshed: associated CRS name: tile;  axis names: ii,jj (corresponding to horizontal and vertical respectively).

**Comment by joanma747** [comment]
If I understand the problem correctly, expressing a position in "tilematrix" coordinates reference system requires 5 numbers: zoom level,  columns, rows, i and j. Columns and rows count tiles in horizontal and vertical while, in this context, i and j are the position of a pixel inside a tile (0 to 255 if tiles are 256 pixels wide).

In the "map" coordinates reference system, i and j has another meaning: horizontal an vertical position in the map area.

I believe it is possible to separate the two meaning of the i and j in the two situations by providing the coordinate reference system type associated with them.

**Comment by prushforth** [comment]
> expressing a position in "tilematrix" coordinates reference system requires 5 numbers: zoom level, columns, rows, i and j

You don't need to know row and column, since the tiled coordinate reference system requires zoom,x,y to identify a position (with spatial resolution being a function of zoom).  

zoom, row, and column are the axes of the tilematrix coordinate system in contrast with the above, which are referred to as "tcrs" in the specification (see this [diagram](https://maps4html.github.io/MapML/spec/#examples))

HOWEVER each tile identified by zoom,row,column has an internal pixel coordinate space with axes known as i and j, with values from 0 to 255 (NOT shown in the diagram, maybe we should have another sub-diagram that highlights the tile coordinate system?? WDYT?).  The problem (if it is a problem, tbd) is that the [map coordinate system](https://maps4html.github.io/MapML/spec/#examples),  also has axes named i and j.  So when the map author uses markup like <input type=location units=map axis=i> and <input type=location axis=i> in one document the author might in the latter case mean units=tile or units=map.  So it forces the author to specify units, and forces us to make units a mandatory attribute.

> I believe it is possible to separate the two meaning of the i and j in the two situations by providing the coordinate reference system type associated with them.

i.e. by having the `location@units` as a mandatory  attribute. OK, I guess I'll close this issue, it can be re-opened if necessary.
