### ISSUE TITLE
WebIDL errors

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/MapML#212]
Some interfaces defined in the original specification were never implemented, and the definitions of them are now flagged by ReSpec,  As such, they can be fixed through removal.  There may be other un-flagged errors especially in the WebIDL interfaces, which have not been properly maintained, I would say. 

cc @erictheise

**Comment by Malvoz** [comment]
Related: https://github.com/Maps4HTML/MapML/issues/80.
