### ISSUE TITLE
Remove or fully specify the `<image>` element

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/MapML#216]
I note that there is still an `image` element, although it's not really specified properly.  I think we should remove it until we're ready to design it a little bit more.  Probably don't want another `image` element in HTML anyway TBD.

**Comment by Malvoz** [comment]
There are related comments in https://github.com/Maps4HTML/MapML/issues/70 that are worth mentioning:

> > - `image`: the HTML parser treats `<image>` as a macro and changes it to `<img>`. New element name?
>
> Maybe `img`? Map images aren't that different from regular images, and instead of extending the set of elements we apply the same re-use of existing semantics but update the rendering model?

It may be better to have a new name as to not be confused with the `<img usemap="">` element (https://github.com/Maps4HTML/MapML/issues/217).
