### ISSUE TITLE
Add Plate Carrée as a TCRS

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/MapML#26]
Let`s treat this as an addition; it was originally requested [here](https://github.com/Maps4HTML/MapML/issues/23#issue-364113409):

> Proposed (from: http://www.opengeospatial.org/standards/requests/169 Table D.3)
> 0.703125000000000
> 0.351562500000000
> 0.175781250000000
> 8.78906250000000 10-2
> 4.39453125000000 10-2
> 2.19726562500000 10-2
> 1.09863281250000 10-2
> 5.49316406250000 10-3
> 2.74658203125000 10-3
> 1.37329101562500 10-3
> 6.86645507812500 10-4
> 3.43322753906250 10-4
> 1.71661376953125 10-4
> 8.58306884765625 10-5
> 4.29153442382812 10-5
> 2.14576721191406 10-5
> 1.07288360595703 10-5
> 5.36441802978516 10-6
> 
> This way (as said in D.3) this one becomes compatible with INSPIRE SDI in Europe.

I support the addition of Plate Carrée (or some more [appropriate](https://en.wikipedia.org/wiki/Equirectangular_projection) mnemonic string identifier) as a TCRS value.  Making this maximally inter-operable with existing INSPIRE services would be ideal. It worries me a little that it is not quite the same as the definition from WMTS 1.0.

However, I don't agree with replacing the definition of WGS84 in the [table of TCRS identifiers](https://maps4html.github.io/MapML/spec/#projections) because WGS84 is how [GeoJSON is served](https://tools.ietf.org/html/rfc7946#section-4), and it's in the GeoJSON marketplace (the Web) that MapML has to compete as well.

**Comment by joanma747** [comment]
Thanks for taking this into consideration. Next version of WMTS will eliminate the discrepancies with the INSPIRE definition.

> However, I don't agree with replacing the definition of WGS84 in the table of TCRS identifiers because WGS84 is how GeoJSON is served, and it's in the GeoJSON marketplace (the Web) that MapML has to compete as well.

I'm more or less fine with it BUT to me it is imperative that you add a NOTE saying that in and extend with @units='WGS84' the values tcrs, tile and tilematrix are NOT allowed in input@units (both are for a tiled spaces that WGS84 does NOT have a tiled space associated). Only pcrs and gcrs should be allowed.

**Comment by prushforth** [comment]
Closing because it is implemented in client and GeoServer.
