### ISSUE TITLE
default account page

### ISSUE THREAD

**Issue by bkardell** [Maps4HTML/MapML#33]
I noticed while looking for this again that what I find easily is http://maps4html.github.io/ which brings up a page that kind of looks like it's an error (it's not, it's just also not especially helpful or purposeful looking).  It would be super nice if that either linked to or redirected you to https://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/ (note the https too)

**Comment by prushforth** [comment]
Yes, that's a good suggestion.  I'm not sure how to make an index page there.  I'll figure it out.  I've got too much stuff, obviously.

**Comment by bkardell** [comment]
Just update this : https://github.com/Maps4HTML/Maps4HTML.github.io/blob/master/index.html

**Comment by prushforth** [comment]
[Done](https://maps4html.github.io/) Thanks

**Comment by AmeliaBR** [comment]
While I agree with Brian's original sentiment (the landing page was very bare-bones), I'm not sure redirecting to one spec out of many is the solution.  But further discussion should happen in the website repo: https://github.com/Maps4HTML/Maps4HTML.github.io
