### ISSUE TITLE
update 'relevant' link

### ISSUE THREAD

**Issue by bkardell** [Maps4HTML/MapML#34]
>  In other words, Web maps with relevant APIs should be available to Web authors and programmers in a declarative, HTML, CSS and JavaScript-compatible manner.

'relevant' links to http://geojson.org/geojson-spec.html which is obsolete and should point to https://tools.ietf.org/html/rfc7946 now

**Comment by prushforth** [comment]
[Fixed](http://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/#introduction)
