### ISSUE TITLE
MapML link is 404

### ISSUE THREAD

**Issue by bkardell** [Maps4HTML/MapML#35]
> Map Markup Language
MapML is a MicroXML-based hypertext format for Web map content, including tiles, vectors, images, links and metadata.

That link is 404

**Comment by prushforth** [comment]
yeah, sorry about that.  This issue is related to [the repo for Use Cases and Requirements](https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements).  I'll open this issue over there.
