### ISSUE TITLE
Specification of multipolygon element

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/MapML#43]
1. The [table ](https://maps4html.github.io/MapML/spec/#geometry-values)contains CamelCase element names, which it shouldn't.  
2. The multipolygon content model says that it contains "Two or more `<coordinates>` elements" , but it should say "Two or more `<polygon>` elements" 

Yes, this is inconsistent with the content models for multilinestring and multipoint. This was done to minimize markup, and adhere to GeoJSON content model to the extent possible in markup.  

Opinions welcome in replies, but I think this is a bikeshed not worth painting.

**Comment by prushforth** [comment]
I believe this relates to the [issue](#) raised by OGC Testbed 15, requesting that MapML eliminate (redundant) `<multipoint><coordinates>`.

**Comment by jerstlouis** [comment]
A single "polygon" within a "multipolygon" should probably also be considered valid.
Same for a single "coordinates" within a "multilinestring".

**Comment by prushforth** [comment]
> A single "polygon" within a "multipolygon" should probably also be considered valid.
> Same for a single "coordinates" within a "multilinestring".

Agreed.

**Comment by prushforth** [comment]
Fixed by https://github.com/Maps4HTML/MapML/commit/513cc32f6dd7eaa1fee35f59619f0e18253eb990
