### ISSUE TITLE
[question] Making the spec(s) more readable

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/MapML#50]
Currently both the [MapML spec](https://maps4html.github.io/MapML/spec/) and [HTML &lt;map&gt; element](https://maps4html.github.io/HTML-Map-Element/spec/) have no width limitations of the text/content, making it hard to read.

I don't know if there are intentions to eventually use ReSpec or something else, however I figured that'll take some time, and is not of priority right now. Potentially we can just add a quick fix to the CSS of these specs? This would include adding a viewport &lt;meta&gt; element in the head, and some extra styles to allow for responsive images and tables, restricting the width to 850px (following what the "use cases and requirements" spec does), and also setting a bigger line-height (`1.5`).

Now, I've already done these things for you to compare with the original look because I thought it'd be fun to test out, and IMO it looks pretty good. The changes include adding 1kb~ of CSS but without modifying html (except from the viewport meta element).

You can view the responsive MapML spec ([fork](https://github.com/Malvoz/MapML)) here: https://raw.githack.com/Malvoz/MapML/gh-pages/spec/index.html (worth noting, due to the width restrictions of the content it is somewhat awkward to scroll overflowing tables on desktop, I created a [second version](https://raw.githack.com/Malvoz/MapML/gh-pages/spec/index2.html) that allows for tables to escape the width restriction to prevent them from overflowing, but personally I don't like how it looks although it may be more user-friendly).

And you can view the responsive &lt;map&gt; element spec ([fork](https://github.com/Malvoz/HTML-Map-Element)) here: https://raw.githack.com/Malvoz/HTML-Map-Element/master/spec/index.html

If for whatever reason you don't want to apply these changes, that's okay of course. If you do, I can PR. ^^

**Comment by Malvoz** [comment]
Before and after comparison on mobile:

![before-after2](https://user-images.githubusercontent.com/26493779/62375785-5bd89b00-b53f-11e9-8179-4cc507b441aa.png)

**Comment by prushforth** [comment]
This is very much appreciated.  I think PRs would work out well.  I agree they are both more readable with the CSS adjustments you've made.  Thank you!

I am hoping that once we are finished our review of use cases and requirements, we can turn our collective attention and efforts to these two works, and at that time we can switch over to ReSpec.  WDYT?  Should start in late September if all goes well.

**Comment by Malvoz** [comment]
> I am hoping that once we are finished our review of use cases and requirements, we can turn our collective attention and efforts to these two works

Yes! :)

Thanks for merging these!
