### ISSUE TITLE
Merge the <map> and <layer> elements into this specification

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/MapML#55]
It is confusing to have two specifications which represent a single proposal.  In MapML, there exist several instances of HTML elements which have proposed new attributes (as well as some new elements).  This makes it not really worthwhile to separate the proposal for extending `<map>` and adding `<layer>` and IIRC, it has been my intention to remove the proposal to extend `<area>`. That removal could be done as part of the merge.

Ideally, as a community, we will become logical maintainers of existing `<img>` `<map>` and `<area>` elements' client side image map functionality, hopefully also providing support for [responsive image maps](https://github.com/Maps4HTML/HTML-Map-Element/issues/22) via the `<picture>` element or CSS, TBD.

**Comment by Malvoz** [comment]
I noticed that "`layer@src`" is mentioned in this spec, but there's currently no reference to https://maps4html.org/HTML-Map-Element/spec/.

**Comment by Malvoz** [comment]
The main issue was resolved by https://github.com/Maps4HTML/MapML/pull/78.

> IIRC, it has been my intention to remove the proposal to extend `<area>`. That removal could be done as part of the merge.

@prushforth the proposal to extend `<area>` was not removed in #78, want to open a new issue for that?

**Comment by prushforth** [comment]
I don't want to mess with legacy code, but I would like to keep the dream alive of giving authors the ability to make `<area>` coordinates responsive.  

That's a different issue than extending the `<area>` coords to support different shapes, and I don't intend to pursue that topic any longer, as I think if we can make the case to implement `<feature>` and `<layer>` there will not be a need for additional shapes.
