### ISSUE TITLE
Deprecate the extent@action attribute, templates are sufficient (for discussion)

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/MapML#61]
The extent@action attribute was created as a first pass at conceiving an encoding of map and layer behaviour in markup, but it turns out that templated links provide a more faithful representation of how maps are actually implemented on the Web today. 

As such, it is proposed to deprecate and remove the extent@action attribute from the MapML spec.

**Comment by Malvoz** [comment]
I take it as `<link tref="">` is sufficient for content retrieval, does this mean the other form related attributes `enctype` and `method` can be removed as well?

**Comment by prushforth** [comment]
> does this mean the other form related attributes enctype and method can be removed as well?

Yes
