### ISSUE TITLE
Some links that need fixing

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/MapML#66]
Edit: Updated to reflect changes in https://github.com/prushforth/MapML/commit/9d3175aa40fbcebe8cb1e4b34ccd4517e6d965aa, TBD:

The [W3C link checker](https://validator.w3.org/checklink?uri=https%3A%2F%2Fmaps4html.org%2FMapML%2Fspec%2F) currently reports:

> Broken fragments:
> https://maps4html.org/MapML/spec/#link-type-author (line 1300)
> https://maps4html.org/MapML/spec/#link-type-license (line 1318)
> https://maps4html.org/MapML/spec/#link-type-legend (line 1312)
> https://maps4html.org/MapML/spec/#rel-alternate (line 1294)
> https://maps4html.org/MapML/spec/#link-type-next (line 1324)
> https://maps4html.org/MapML/spec/#ref-Schema2 (line 2167)
> https://maps4html.org/MapML/spec/#link-type-bookmark (line 1306)

**Comment by prushforth** [comment]
> https://maps4html.org/MapML/spec/#link-type-legend (line 1323)
> https://maps4html.org/MapML/spec/#link-type-bookmark (line 1317)
> https://maps4html.org/MapML/spec/#link-type-next (line 1335)
> https://maps4html.org/MapML/spec/#link-type-license (line 1329)
> https://maps4html.org/MapML/spec/#link-type-author (line 1311)

I think these links should be removed.  I may have  *intended* to provide a cross-reference to their definitions, as I likely got the markup out of the HTML specification.  Some of them have HTML definitions already, and some are inventions of MapML.  I don't really have more elaborate definitions for the ones we introduce than exist in that table. 

> https://maps4html.org/MapML/spec/#the-polygon-element (line 2092)

I fixed the table of geometry elements by adding id attribute for each geometry type, with cross-references as appropriate.

> https://maps4html.org/MapML/spec/#ref-Schema2 (line 2180)

Fixed

> https://maps4html.org/MapML/spec/#tiled-CRS (line 1538)

Fixed. Replaced with "#tiled-coordinate-reference-systems-table"

> https://maps4html.org/MapML/spec/#ref-XML11-SCHEMA (line 2225)

Had to add a reference. I'm not sure it comes into play, but I added it before, so trusting there was a reason.

> The "Latest version" is pointing to the old URL so I think we can at least update that one.

Where should I update it to point at, do you think?

**Comment by Malvoz** [comment]
> Where should I update it to point at, do you think?

https://maps4html.github.io/MapML/spec/ redirects to https://maps4html.org/MapML/spec/ so while it's technically fine to keep it as-is people might think it's a separate document, and since it says "Latest version" they'll probably be inclined to click it only to be redirected to the page they were currently on.
