### ISSUE TITLE
[docs][bug] Two 4.2.1 sections

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/MapML#67]
If you navigate to https://maps4html.org/MapML/spec/#documents you'll find that there are 2 sections both numbered 4.2.1.

> ``` html
> <h4 id="documents">4.2.1 Elements</h4>
> ```
> ```html
> <h4 id="the-document-object">
>    <span class="secno">4.2.1 </span>The <code><a href="#the-document-object">Document</a</code> object
> </h4>
> ```

**Comment by prushforth** [comment]
Oops
