### ISSUE TITLE
Use of "Metadata content" in <layer>'s content model

### ISSUE THREAD

**Issue by zcorpan** [Maps4HTML/MapML#84]
> Content model:
> If the src attribute is present: Empty. If no src attribute is present: Metadata content describing nested Map Markup Language content

"Metadata content" is a specific list of HTML elements, plus "Elements from other namespaces whose semantics are primarily metadata-related (e.g. RDF) are also metadata content."
https://html.spec.whatwg.org/multipage/dom.html#metadata-content-2

If you want to allow only MapML elements here, don't use "metadata content".

**Comment by prushforth** [comment]
> > If you want to allow only MapML elements here, don't use "metadata content".
> 
> When you create MapML content in the layer DOM this way, you're going to need sometimes to establish metadata about the content, such as the zoom range and bounds it should be displayed in, which I think we are thinking could be provided by the `<meta>` element, which otherwise might have been provided in the `<head>` element of the document fetched from `layer@src`.

For instance, see [the example in this page](https://maps4html.org/web-map-doc/docs/layers/layer/).  The second \<layer-> element has "inline" metadata content, plus MapML described by the metadata.  I can imagine how some [the current specific list of elements defined as "metadata content" apply](https://html.spec.whatwg.org/multipage/dom.html#metadata-content-2) (e.g. base, meta, link, style, title) but not others (e.g. script, noscript and template).

> If you want to allow only MapML elements here, don't use "metadata content".

What do you [suggest](https://github.com/Maps4HTML/MapML/issues/206)?

**Comment by zcorpan** [comment]
What is the exact list of elements you want to allow in `layer`?

**Comment by Malvoz** [comment]
I believe the layer element (without a `src` attribute that is) allows:

- The following metadata elements:
  - [`<meta>`](https://maps4html.org/MapML/spec/#the-meta-element)
  - [`<link>`](https://maps4html.org/MapML/spec/#the-link-element)
  - [`<style>`](https://github.com/Maps4HTML/MapML/issues/209)
  - perhaps other non-scripting metadata elements, though AFAICT there's no need for those
- [`<extent>`](https://maps4html.org/MapML/spec/#the-extent-element)
  - [`<input>`](https://maps4html.org/MapML/spec/#the-input-element)
  - [`<datalist>`](https://maps4html.org/MapML/spec/#the-datalist-element)
  - [`<label>`](https://maps4html.org/MapML/spec/#the-label-element)
  - [`<select>`](https://maps4html.org/MapML/spec/#the-select-element)
  - [`<option>`](https://maps4html.org/MapML/spec/#the-option-element)
- [`<feature>`](https://maps4html.org/MapML/spec/#the-feature-element)
  - [`<featurecaption>`](https://maps4html.org/MapML/spec/#the-featurecaption-element)
  - [`<properties>`](https://maps4html.org/MapML/spec/#the-properties-element)
  - [`<geometry>`](https://maps4html.org/MapML/spec/#the-geometry-element)
    - [`<a>`](https://github.com/Maps4HTML/MapML/issues/181)
    - [geometries](https://maps4html.org/MapML/spec/#geometry-values)
      - [`<coordinates>`](https://maps4html.org/MapML/spec/#the-coordinates-element)
  - <s>[`<image>`](https://github.com/Maps4HTML/MapML/issues/216)</s>
- [`<tile>`](https://maps4html.org/MapML/spec/#the-tile-element)

i.e. allowed children are: a subset of HTML metadata elements, `extent`, `feature`, and `tile`.

@prushforth does this look correct to you?

**Comment by prushforth** [comment]
### Metadata content

>   
>   * [`<meta>`](https://maps4html.org/MapML/spec/#the-meta-element)
>   * [`<link>`](https://maps4html.org/MapML/spec/#the-link-element)
>   * [`<style>`](https://github.com/Maps4HTML/MapML/issues/209)
>   * perhaps other non-scripting metadata elements, though AFAICT there's no need for those

Looks pretty good.  Add:

* [\<base>](https://maps4html.org/MapML/spec/#the-base-element-0)
* [\<title>](https://maps4html.org/MapML/spec/#the-title-element-0)

I don't think we have thought of a map-specific use for \<script>, \<noscript> or \<template>, but if they fill out the role of "metadata content", is it simpler to allow them or to create a new content category?

### Not metadata content

* [\<tile>](https://maps4html.org/MapML/spec/#the-tile-element-0) is like a square/rectangular feature, so it is not a child of extent

FWIW I think \<image> is an anachronism, and we [could](https://github.com/Maps4HTML/MapML/issues/216) get rid of it.

We would eventually like discuss how to (use CSS to) absolutely position and style other HTML content that gets rendered on the map; we would like to allow such elements to be rendered and panned/zoomed (as suits the author), or hidden (depending on map scale, perhaps), with the map in a standard fashion.

**Comment by Malvoz** [comment]
> Looks pretty good. Add:
>
> - [&lt;base>](https://maps4html.org/MapML/spec/#the-base-element-0)
> - [&lt;title>](https://maps4html.org/MapML/spec/#the-title-element-0)

I can see the usefulness of these elements in mapml documents, but since we're discussing the layer element's content model (in an HTML document):

- Per the HTML spec, there can only be one `<base>` element per document. So authors may as well use it in HTML `<head>`?
  I don't suppose we're intending to change the definition of HTML `<base>`? Am I missing something?
- Is `<title>` needed (outside of mapml documents)? We already have `<layer label="">`.
  I suppose it could be allowed, and `label` take precedence, as is the case with external mapml documents?

Perhaps it's time to discuss https://github.com/Maps4HTML/MapML/issues/210?

> I don't think we have thought of a map-specific use for &lt;script>, &lt;noscript> or &lt;template>, but if they fill out the role of "metadata content", is it simpler to allow them or to create a new content category?

For MapML documents I think it's been said they're a security concern, but maybe the correct thing to do is allow them, and leave it up to authors to use CSP `script-src` accordingly?

> [&lt;tile>](https://maps4html.org/MapML/spec/#the-tile-element-0) is like a square/rectangular feature, so it is not a child of extent

Oops, I've corrected my comment.

**Comment by prushforth** [comment]
> Per the HTML spec, there can only be one \<base> element per document. 

OK, I didn't realize that.  We include \<map-base> element processing when processing a remote text/mapml response in our polyfill, and the processing is very naive compared with the HTML spec.  Further, while the polyfill does process inline MapML, it doesn't use the distinction of inline vs remote document in its logic, such as whether to ignore a found \<map-base> element, it just uses the provided URL as a base URL to resolve other found URLs against (which obviously does not conform to HTML).  We need a way to specify some (layer) metadata inline, without having to have an inline \<map-head> element, which is also obviously not an HTML construct.

> Is <title> needed (outside of mapml documents)? We already have <layer label="">.
I suppose it could be allowed, and label take precedence, as is the case with external mapml documents?

The polyfill behaviour has changed about whether a provided \<title> will take precedence, IIRC.    Currently, a map author-provided \<map-title> takes precedence, with a fallback to \<layer- \@label="..."> regardless of whether the content is inline or a remote document.  That could be wrong, fwiw.  I was thinking about honouring the intentions of the cartographer / map author in that implementation.  

Getting back to @zcorpan's original comment:

> If you want to allow only MapML elements here, don't use "metadata content".

We want to allow some of the elements categorized as "metadata content", plus a set of map content elements.  [Robert's comment ](https://github.com/Maps4HTML/MapML/issues/84#issuecomment-1088023028) provides the current respective element lists.  

Maybe we should coin specification terms such as "map (or layer) metadata content" and "map content"?
