### ISSUE TITLE
Errors in IDL

### ISSUE THREAD

**Issue by zcorpan** [Maps4HTML/MapML#90]
```
[NamedConstructor=Map(unsigned long width, unsigned long height, double lat, double lon, unsigned short zoom, optional string projection, boolean controls)]
interface HTMLMapElement : HTMLElement {
   readonly attribute HTMLCollection layers;
   readonly attribute HTMLCollection areas;
   readonly attribute unsigned short zoom;
   readonly attribute double lat;
   readonly attribute double lon;
   readonly attribute string projection;
   attribute boolean controls;
   attribute unsigned long width;
   attribute unsigned long height;
   void zoomTo(double latitude, double longitude, optional unsigned short zoom);
};
```

- `string` should be `DOMString`
- `[Exposed=Window]` is missing
- `[HTMLConstructor] constructor();` is missing
- IDL attributes that reflect content attributes should have `[CEReactions]`
- IDL attributes that return `HTMLCollection` should have `[SameObject]`
- `NamedConstructor` was [changed](https://github.com/heycam/webidl/pull/870) to `[LegacyFactoryFunction]`.

see https://html.spec.whatwg.org/multipage/image-maps.html#the-map-element

**Comment by Malvoz** [comment]
It should be noted that while some errors exist, most of the ones described above were fixed in https://github.com/Maps4HTML/MapML/pull/126/commits/bcfeb6af07cbeed0a5c0d8af226e87bf59cd9713.

**Comment by Malvoz** [comment]
AFAIK these are all fixed:

> - `string` should be `DOMString`
> - `[Exposed=Window]` is missing
> - `[HTMLConstructor] constructor();` is missing
> - IDL attributes that reflect content attributes should have `[CEReactions]`
> - IDL attributes that return `HTMLCollection` should have `[SameObject]`
> - `NamedConstructor` was [changed](https://github.com/heycam/webidl/pull/870) to `[LegacyFactoryFunction]`.

Closing in favor of https://github.com/Maps4HTML/MapML/issues/212 for the remaining issues.
