### ISSUE TITLE
Why named constructor - is window.Map web-compatible?

### ISSUE THREAD

**Issue by zcorpan** [Maps4HTML/MapML#94]
> [NamedConstructor=Map(unsigned long width, unsigned long height, double lat, double lon, unsigned short zoom, optional string projection, boolean controls)]

Why provide a named constructor? Is it web-compatible to add "Map" to the global scope?

**Comment by prushforth** [comment]
I think this is [fixed](https://maps4html.org/MapML/spec/#webidl-1786032469). Closing for now.
